### ISSUE TITLE
todo fusion

### ISSUE THREAD

**Issue by markblundeberg** [markblundeberg/Electron-Cash#1]
Critical::
- [x] Blockchain checking during blame is still TODO.
- [x] Client needs sensible limits on feerate and excess_fee, so a malicious server can't cause them to blast everything into miner fees.
- [x] Test server prevents multiple players from same IP going in same round. (But they may wait together)
- [x] Fix bugs. (see other Issues)
- [x] Coin chooser tweaking. -- Better coin fraction selection. Whale wallets may want to fuse at lower tiers. Some users may want to consolidate down to fewer utxo.

Important:
- [x] Fusions watch their source coins and stop themselves if coins are spent. (this is especially important when still in waiting pool since it's not too late to avoid blame)
- [x] *Waiting* autofusions stop when user stops autofusion. Not sure what to do about in-progress.
- [ ] Client and server detection on 'sensibly private' fusions and aborting (based on examining components).
- [ ] When stopping wallets, need a way for user to stop it cold so they don't have to wait forever.
- [ ] Sanity protections against infinite rounds, both client and server. (what happens when nobody is blamed?)
- [x] Error indicator when fusion just isn't working right, and a clear diagnostic. Some kind of (!) icon in statusbar.
  - Network errors
  - Can't-find-a-tier errors
  - Fusion procedural failures
- [ ] Make it less net-spammy when doing auto fusions which constantly fail. Need to remember the server's last greeting params message, and do a connection AFTER selecting outputs. See #13
- [x] Greeting should indicate something like: height, tip hash and prevhash. Clients can use this to identify if they're on different chain.
- [x] Complete fusions need a wait time after done, before unfreezing coins. If the transaction hasn't shown up in wallet yet then another fusion might mistakenly grab one of those coins. (it will likely harmlessly fail due to the periodic input spend sanity check, but it could happen it starts rounds too soon)
- [x] Lighten the Tor connection load: see https://github.com/markblundeberg/Electron-Cash/issues/8 .
- [x] Better UX for wallet parameter selection ('consolidation mode' etc.)
- [ ] Rate limiting on fusions, for people who want to leave it running constantly
- [ ] Add metadata tracking, add limit on fusion depth for people who just want to increase privacy sligthly and don't want to be burning fees all day long.
- [ ] (BIG work) make electron cash / cash fusion actually provide privacy (marking coins, spending them appropriately).

Wishlist:
- [ ] #20 - Variable number of commitments/components per player.
  - Note: max_excess_fee should now be max_excess_fee_per_component.
  - Players need to announce their component count during pool registry, to avoid absurd fee condition and so the server knows how many blind nonces to send during round start.
  - Question: what random distribution should client use to choose number of excess (blank) components?
- [x] Easier Tor for users (at first just find tor installation, later do bundling?)
- [ ] Clean up race condition between coin selection and coin-freezing. (esp in user selection)
- [x] Test server SSL. Note the server needs to know its host so it can issue covert host correctly.
- [ ] For manually-started fusions make a window that shows progress / allows restarting / etc..
- [x] Sometimes we want to cancel stale autofusions and try new ones, since wallet may have new coins, or we might want to try different tiers.
- [x] Better user-friendly diagnostic panel.
- [ ] Whale splitter and whale consolidator (having a single giant input or output that gets peeled off, or built up).
- [ ] #21- Automatic address consolidation for addresses with many utxo. (Currently, Fusion ignores addrs with >3 coins)
